ALTER TABLE tbl_user ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
ALTER TABLE tbl_resident ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
   ALTER TABLE tbl_blotter MODIFY contact VARCHAR(20) NOT NULL;