<?php
require_once 'classes/Authentication.php';
require_once 'classes/Notification.php';
require_once 'classes/resident.class.php';

$auth = new Authentication();
$notification = new Notification();
$resident = new Resident();

// Test data - using valid IDs from database
$test_resident_id = 25; // Jun Trinidad
$test_certificate_id = 3; // Business permit ID 3

echo "<h2>Testing Business Permit Notification System</h2>";

// Test 1: Check if resident exists
echo "<h3>Test 1: Resident Data</h3>";
$resident_data = $resident->get_single_resident($test_resident_id);
if ($resident_data) {
    echo "✅ Resident found: " . $resident_data['fname'] . ' ' . $resident_data['lname'] . "<br>";
    echo "Email: " . $resident_data['email'] . "<br>";
    echo "Contact: " . $resident_data['contact'] . "<br>";
} else {
    echo "❌ Resident not found<br>";
    exit;
}

// Test 2: Check business permit data
echo "<h3>Test 2: Business Permit Data</h3>";
require_once 'classes/conn.php';
$conn = new PDO("mysql:host=localhost;dbname=bmis", "root", "");
$stmt = $conn->prepare("SELECT * FROM tbl_bspermit WHERE id_bspermit = ?");
$stmt->execute([$test_certificate_id]);
$permit_data = $stmt->fetch(PDO::FETCH_ASSOC);

if ($permit_data) {
    echo "✅ Business permit found: ID " . $permit_data['id_bspermit'] . "<br>";
    echo "Business Name: " . $permit_data['bsname'] . "<br>";
    echo "Notification Status: " . ($permit_data['notification_sent'] ? 'Sent' : 'Not Sent') . "<br>";
} else {
    echo "❌ Business permit not found<br>";
    exit;
}

// Test 3: Send notification
echo "<h3>Test 3: Sending Notification</h3>";
$recipient_data = [
    'email' => $resident_data['email'],
    'contact' => $resident_data['contact'],
    'full_name' => $resident_data['fname'] . ' ' . $resident_data['mi'] . ' ' . $resident_data['lname']
];

$service_data = [
    'service_type' => 'Business Permit',
    'certificate_number' => $test_certificate_id,
    'date' => date('Y-m-d'),
    'generated_date' => date('Y-m-d H:i:s')
];

$notification_result = $notification->sendServiceNotifications($recipient_data, $service_data, 'ready');

echo "Email sent: " . ($notification_result['email_sent'] ? 'Yes' : 'No') . "<br>";
echo "SMS sent: " . ($notification_result['sms_sent'] ? 'Yes' : 'No') . "<br>";

// Test 4: Create system notification
echo "<h3>Test 4: System Notification</h3>";
$title = $service_data['service_type'] . ' Ready';
$message = "Your {$service_data['service_type']} is ready for collection at Nyarutarama Cell Office.";
$system_notification = $notification->createSystemNotification($test_resident_id, 'business_permit', $title, $message);

if ($system_notification) {
    echo "✅ System notification created successfully<br>";
} else {
    echo "❌ Failed to create system notification<br>";
}

// Test 5: Update notification status
echo "<h3>Test 5: Update Notification Status</h3>";
$update_result = $notification->updateServiceNotificationStatus('tbl_bspermit', 'id_bspermit', $test_certificate_id, 'Test Admin');

if ($update_result) {
    echo "✅ Notification status updated successfully<br>";
} else {
    echo "❌ Failed to update notification status<br>";
}

// Test 6: Verify database update
echo "<h3>Test 6: Verify Database Update</h3>";
$stmt = $conn->prepare("SELECT notification_sent, notification_date, generated_by, generated_date FROM tbl_bspermit WHERE id_bspermit = ?");
$stmt->execute([$test_certificate_id]);
$updated_data = $stmt->fetch(PDO::FETCH_ASSOC);

if ($updated_data) {
    echo "Notification sent: " . ($updated_data['notification_sent'] ? 'Yes' : 'No') . "<br>";
    echo "Notification date: " . $updated_data['notification_date'] . "<br>";
    echo "Generated by: " . $updated_data['generated_by'] . "<br>";
    echo "Generated date: " . $updated_data['generated_date'] . "<br>";
}

echo "<h3>Test Complete!</h3>";
echo "Business permit notification system is working correctly.";
?>